id: P005397
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS19936
  title: ལྟུང་བཤགས་ཀྱི་འགྲེལ་པ།
  author: ''
  volumes:
    fe319b1ac5304146803047e8e3447d98:
      image_group_id: I8LS19938
      title: ''
      volume_number: 1
      total_pages: 48
      base_file: v001.txt
