id: IE2438A1E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:34:49+00:00'
last_modified: '2022-06-08T02:47:42.605929+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19936
  title: ལྟུང་བཤགས་ཀྱི་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D825:
      image_group_id: I8LS19938
      title: ''
      total_pages: 48
      order: 1
      base_file: D825.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
